app:
  env: LOCAL
  name: go-rest-example
  port: 8080
  logFormat: text
  timeout: 60s
postgres:
  master:
    dbName: postgres
    host: localhost
    password: dhukidwirachman
    port: 5432
    schema: public
    user: dhukidwirachman
    debug: false
  slave:
    dbName: postgres
    host: localhost
    password: dhukidwirachman
    port: 5432
    schema: public
    user: dhukidwirachman
    debug: false
  maxIdleConnections: 10
  maxOpenConnections: 10
  setConMaxIdleTime: 10
  connectTimeout: 10
redis:
  host: localhost:6379
  db: 0
  password: